# This is a basic workflow to help you get started with Actions
# This is a basic workflow to help you get started with Actions

name: CI/CD 2

name: Push to DockerHub

on:
  push:
    branches:
      - 'master'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run unit tests
        run: ./gradlew test
      - name: Build
        run: ./gradlew build
      - uses: actions/upload-artifact@master
        with:
          name: springdemo-0.0.1-SNAPSHOT.jar 
          path: ./build/libs/springdemo-0.0.1-SNAPSHOT.jar
  push-to-dockerhub:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - uses: actions/download-artifact@master
        with:
          name: springdemo-0.0.1-SNAPSHOT.jar 
          path: ./build/libs/springdemo-0.0.1-SNAPSHOT.jar
      - name: Build Docker image
        run: docker build -t johanmathew/welcome-app .
      - name: Test Docker Container
        run: docker run -rm johanmathew/welcome-app
      - name: Push Docker Image
        run: docker push johanmathew/welcome-app

      
